### ISSUE TITLE
Error in heasarc.py

### ISSUE THREAD

**Issue by CoriFletcher-USRA** [USRA-STI/gdt-core#14]
from gdt.core.heasarc import BrowseCatalog

Error Returned:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File gdt-core/src/gdt/core/heasarc.py", line 379, in <module>
    class FileDownloader(BaseFinder):
  File "gdt-core/src/gdt/core/heasarc.py", line 402, in FileDownloader
    def bulk_download(self, urls: list[str], dest_dir: Union[str, Path], verbose: bool = True):
TypeError: 'type' object is not subscriptable

**Comment by AdamGoldstein-USRA** [comment]
What version of python are you using?  I ran the import statement in 3.9.16 and it does not produce this error.

**Comment by AdamGoldstein-USRA** [comment]
Also, make sure that you have the latest version (2.0.2).  I believe there was an update for this or a related issue.
