### ISSUE TITLE
matplotlib AttributeError: 'Colorbar' object has no attribute 'patch'

### ISSUE THREAD

**Issue by CoriFletcher-USRA** [USRA-STI/gdt-core#20]
It seems like the patch option only works for matplotlib<=3.6.3 for some of the plotting schemes in the gdt core.

**Comment by AdamGoldstein-USRA** [comment]
Can you add more detail?  What is the error, and what did you do to get the error?

**Comment by CoriFletcher-USRA** [comment]
When iI try to create the response matrix plot using drmplot = ResponsePlot(rsp.drm)

I get the error: 
AttributeError: 'Colorbar' object has no attribute 'patch'

**Comment by BillCleveland-USRA** [comment]
@CoriFletcher-USRA Need more information related to this.

**Comment by AdamGoldstein-USRA** [comment]
Addressed in PR #56.
