### ISSUE TITLE
healpix convolve does not preserve header information

### ISSUE THREAD

**Issue by joshuarwood** [USRA-STI/gdt-core#28]
https://github.com/USRA-STI/gdt-core/blob/018acb32c52c1f5571d3e66770156b43a365facb/src/gdt/core/healpix.py#L106

Currently trigtime is the only property saved when returning a HealPix-derived class from the convolve function.

In practice, this means a user trying to convolve a systematic error with a GBM map will receive a map with header, scpos, and quaternion information stripped away. Is this the intended behavior? Should users be expected to re-apply that information to the returned map?

**Comment by AdamGoldstein-USRA** [comment]
I'm not sure we want to *require* passing of that information, especially if it doesn't exist for some scenario/mission.  But this does highlight an oversight that this method should have been overwritten in the [GbmHealPix ](https://github.com/USRA-STI/gdt-fermi/blob/ad6c3c3995efe8138ef170504ecf68a6786dc67e/src/gdt/missions/fermi/gbm/localization.py#L49) class.  In that method, it would be appropriate to pass the header, quaternion, and sc position.  Should open an issue in gdt-fermi.

**Comment by joshuarwood** [comment]
Yeah, I completely agree after looking at this in more detail over the afternoon. The issue I'm having relates more to the buggy / inconsistent header behavior reported in your latest merge: https://github.com/USRA-STI/gdt-fermi/commit/ad6c3c3995efe8138ef170504ecf68a6786dc67e

I'll try the latest main branch to see if it solves the issues I'm having. I'll close out this issue.
