### ISSUE TITLE
"Nan" 'el' Values from 'gdt.core.coords.spacecraft', SpacecraftFrame. 

### ISSUE THREAD

**Issue by sumanbala2210-USRA** [USRA-STI/gdt-core#41]
Sollution

@a_coords.frame_transform_graph.transform(a_coords.FunctionTransform, a_coords.ICRS, SpacecraftFrame)
def icrs_to_spacecraft_mod(icrs_frame, sc_frame):
    """
    Modified child class of 'icrs_to_spacecraft' to remove 'Nan' vale of 'el'.
    
    """
    xyz = icrs_frame.cartesian.xyz.value
    rot = Rotation.from_quat(sc_frame.quaternion)
    xyz_prime = rot.inv().apply(xyz.T)
    if xyz_prime.ndim == 1:
        xyz_prime = xyz_prime.reshape(1, -1)
    az = np.arctan2(xyz_prime[:, 1], xyz_prime[:, 0])
    mask = (az < 0.0)
    az[mask] += 2.0 * np.pi
    el = np.pi / 2.0 - np.arccos(np.clip(xyz_prime[:, 2],-1,1)). ###### np.clip helps to avoid the Nan values
    return type(sc_frame)(az=az * u.radian, el=el * u.radian,
                            quaternion=sc_frame.quaternion)

**Comment by AdamGoldstein-USRA** [comment]
The fix was implemented in PR #45.
