### ISSUE TITLE
Slow TTE file read behavior

### ISSUE THREAD

**Issue by joshuarwood** [USRA-STI/gdt-core#43]
I noticed that opening TTE files takes about 3x longer when using GDT compared to older GBM data tools. The slowdown traces to a `list(events)` conversion happening inside the data_primitives.EventList class

https://github.com/USRA-STI/gdt-core/blob/main/src/gdt/core/data_primitives.py#L505

This can be avoided by first creating an empty numpy array and then filling it with the TIME and PHA columns

```
self._events = np.empty(times.size, dtype=[('TIME', times.dtype.type),
                                  ('PHA', channels.dtype.type)])
self._events['TIME'] = times
self._events['PHA'] = channels
```

Filling the empty array takes ~0.06 sec on a 2019 Macbook Pro versus 1 sec for the list conversion. I'll work on a pull request with this suggested change.

**Comment by AdamGoldstein-USRA** [comment]
Merged the solution so I will now close this issue.
