### ISSUE TITLE
Matplotlib version issue with get_cmap

### ISSUE THREAD

**Issue by CoriFletcher-USRA** [USRA-STI/gdt-core#47]
https://github.com/USRA-STI/gdt-core/blob/f94bcbea6a6b2eabfa94e8d56733653653175361/src/gdt/core/plot/plot.py#L256C8-L256C53

The newest version of matplotlib doesnt like plt.cm.get_cmap(), it needs to be updated to plt.get_cmap() for anything newer than 3.9.0

**Comment by AdamGoldstein-USRA** [comment]
Addressed in PR #56.
