### ISSUE TITLE
Problem with "gdt.core.plot.lightcurve import Lightcurve"

### ISSUE THREAD

**Issue by sumanbala2210-USRA** [USRA-STI/gdt-core#48]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[6], line 1
----> 1 from gdt.core.plot.lightcurve import Lightcurve

File ~/software/notebook_catalog_background_fit/gdt/gdt-core/src/gdt/core/plot/lightcurve.py:30
      1 # CONTAINS TECHNICAL DATA/COMPUTER SOFTWARE DELIVERED TO THE U.S. GOVERNMENT WITH UNLIMITED RIGHTS
      2 #
      3 # Contract No.: CA 80MSFC17M0022
   (...)
     27 # License.
     28 #
     29 import numpy as np
---> 30 from .plot import GdtPlot, Histo, HistoErrorbars, HistoFilled, \
     31     LightcurveBackground
     32 from .lib import *
     33 from .defaults import *

File ~/software/notebook_catalog_background_fit/gdt/gdt-core/src/gdt/core/plot/plot.py:38
     36 from matplotlib.figure import Figure
     37 from matplotlib.ticker import AutoMinorLocator
---> 38 from .lib import *
     39 from gdt.core.collection import DataCollection
     41 __all__ = ['DetectorPointing', 'EarthLine', 'EarthPoints', 'EffectiveArea',
     42            'GalacticPlane', 'GdtCmap', 'GdtPlot', 'Heatmap', 'Histo', 
     43            'HistoErrorbars', 'HistoFilled', 'LightcurveBackground',
     44            'ModelData', 'ModelSamples', 'PlotElement', 'PlotElementCollection',
     45            'SAA', 'SkyAnnulus', 'SkyHeatmap', 'SkyCircle', 'SkyLine', 
     46            'SkyPoints', 'SkyPolygon', 'SpectrumBackground', 'Sun']

File ~/software/notebook_catalog_background_fit/gdt/gdt-core/src/gdt/core/plot/lib.py:38
     35 from scipy.spatial.transform import Rotation
     37 from .defaults import *
---> 38 from gdt.core.data_primitives import EnergyBins
     39 from gdt.core.coords import SpacecraftFrame
     41 __all__ = ['earth_line', 'earth_points', 'effective_area', 'errorband', 
     42            'galactic_plane', 'histo', 'histo_errorbars', 'histo_filled', 
     43            'lightcurve_background', 'response_matrix', 'saa_polygon',
     44            'selection_line', 'selections',  'sky_annulus','sky_circle', 
     45            'sky_heatmap', 'sky_line', 'sky_point', 'sky_polygon',
     46            'spectrum_background']

File ~/software/notebook_catalog_background_fit/gdt/gdt-core/src/gdt/core/data_primitives.py:31
     29 import numpy as np
     30 from scipy.interpolate import interp1d
---> 31 from scipy.integrate import trapz
     32 import copy
     34 __all__ = ['Range', 'TimeRange', 'EnergyRange', 'Intervals', 'Gti', 'Ebounds',
     35            'EventList', 'Bins', 'ExposureBins', 'ChannelBins', 'TimeBins', 
     36            'EnergyBins', 'TimeChannelBins', 'TimeEnergyBins', 'ResponseMatrix', 
     37            'Parameter']

ImportError: cannot import name 'trapz' from 'scipy.integrate'

**Comment by AdamGoldstein-USRA** [comment]
@sumanbala2210-USRA can you provide more information on what version of scipy you are using?

**Comment by sumanbala2210-USRA** [comment]
It was with Scipy 1.14 I think. With Scipy 1.12 it is working.

**Comment by BillCleveland-USRA** [comment]
This is being addressed by "whc_api_updates" branch.

**Comment by AdamGoldstein-USRA** [comment]
Address in PR #56.
