### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by atrigg2** [USRA-STI/gdt-core#5]
I’m currently trying to install GDT on my computer and I’ve run into an issue that I can’t figure out. I used the pip install command as it says on the docs page. However, when I run gdt-data init I receive the following error:

Traceback (most recent call last):
  File "/home/unholysun/Documents/GDT/GDT/bin/gdt-data", line 44, in <module>
    from gdt.core.heasarc import FileDownloader
  File "/home/unholysun/Documents/GDT/GDT/lib/python3.8/site-packages/gdt/core/heasarc.py", line 379, in <module>
    class FileDownloader(BaseFinder):
  File "/home/unholysun/Documents/GDT/GDT/lib/python3.8/site-packages/gdt/core/heasarc.py", line 402, in FileDownloader
    def bulk_download(self, urls: list[str], dest_dir: Union[str, Path], verbose: bool = True):
TypeError: 'type' object is not subscriptable

I’m not sure if this is user error or perhaps something specific to my setup. I’m running Ubuntu through WSL2 in Windows 11. I have all required packages for the requierments.txt file installed and a virtual environment set up.

**Comment by RANJITHROSAN17** [comment]
One possible cause of this error could be that you are using a version of Python that is not compatible with the GDT package. It's also possible that there is a bug in the GDT code itself.

To troubleshoot this issue, you could try a few things:

Check the version of Python that you are using. Make sure it is compatible with the GDT package. You can do this by running python --version in your terminal.

Make sure that you have installed all the required dependencies for the GDT package, including any specific version requirements. You can check the requirements.txt file to see what dependencies are needed.

**Comment by BillCleveland-USRA** [comment]
@atrigg2 I wasn't able to reproduce your error on my installation of Ubuntu 22.04 through WSL2 on Windows 11.  My Ubuntu install uses Python 3.10.6.  It may be an issue with Python 3.8. can you post the output of `lsb_release -a` and `python3 --version`?

**Comment by atrigg2** [comment]
@BillCleveland-USRA  Here s the info you requested

(GDT) unholysun@LSU-Machine:~/Documents/GDT$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
(GDT) unholysun@LSU-Machine:~/Documents/GDT$ python3 --version
Python 3.8.10

**Comment by BillCleveland-USRA** [comment]
Thanks. I installed Ubuntu 20.04 LTS and was able to reproduce your error.  I'll work the issue.

**Comment by BillCleveland-USRA** [comment]
@atrigg2 The problem was caused by a type in a method declaration where "list[str]" was used instead of "List[str]".  Apparently this is not an issue for the later versions of Python. I released a minor update, and the update should by on PyPI now.

To update your install use `pip install --upgrade astro-gdt`

**Comment by atrigg2** [comment]
@BillCleveland-USRA This appears to have fixed the issue. I no longer get the error message when trying to use GDT. Thanks!
