### ISSUE TITLE
Spectral fit plot failure in Matplotlib 3.7

### ISSUE THREAD

**Issue by AdamGoldstein-USRA** [USRA-STI/gdt-core#53]
Plotting fails with the following error in Matplotlib v 3.7:

> AttributeError: 'Legend' object has no attribute 'legendHandles'

This is because `Legend.legendHandles` was deprecated in favor of `Legend.legend_handles` according to the [Matplotlib release notes](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#legend-legendhandles).

**Comment by BillCleveland-USRA** [comment]
This is being addressed  in the "whc_api_updates" branch

**Comment by AdamGoldstein-USRA** [comment]
Addressed in PR #56.
