### ISSUE TITLE
Asymmetric errors in SpectralFitter return incorrect values when setting parameters as fixed

### ISSUE THREAD

**Issue by AdamGoldstein-USRA** [USRA-STI/gdt-core#54]
Once a spectral fit is performed, the [SpectralFitter.asymmetric_errors()](https://astro-gdt.readthedocs.io/en/latest/api/gdt.core.spectra.fitting.SpectralFitter.html#gdt.core.spectra.fitting.SpectralFitter.asymmetric_errors) method calculates the asymmetric errors for each free parameter in the fit.  However, there appears to be a bug whenever one fixes a parameter in the function and the fixed parameter is not the last in the list.  This causes an off-by-one indexing issue for each fixed parameter in the fitted function.

The solution is to create a list of indices into the full parameter list and mask out the parameters that are fixed:
`idx = np.arange(self._function.nparams)[np.array(self._function.free)]` 

Then, when finding the lower/upper bounds, the index into the parameter minimum/maximum bounds should be adjusted from the following, e.g.

`minval = self._function.min_values[i]`

should become

`minval = self._function.min_values[idx[i]]`

**Comment by AdamGoldstein-USRA** [comment]
After more inspection, it looks like this bug crops up in the following conditions:
1. There is at least one parameter that is fixed and that parameter is not the last in the parameter list of the function
AND
2. The parameter minimum/maximum allowable bounds is -/+ inf.
OR
3. Condition 1 is true AND the parameter error falls on the minimum/maximum allowable bounds.

If conditions 1+2 are satisfied, the resulting parameter errors may not be incorrect, but finding the parameter errors may be suboptimal. If conditions 1+3 are satisifed, then the parameter errors for the parameters where condition 3 is met will be incorrect.

**Comment by BillCleveland-USRA** [comment]
Issue addressed by merge.
