### ISSUE TITLE
Matplotlib API issues

### ISSUE THREAD

**Issue by joshuarwood** [USRA-STI/gdt-core#68]
Caught instances of plotting bugs related to changes in the matplotlib API during testing of the gdt-fermi notebooks.

1. cb.draw_all() --> cb._draw_all()
https://github.com/USRA-STI/gdt-core/blob/6f9b15ae75b9a8fab9652ec883f9735135c62ebf/src/gdt/core/plot/plot.py#L836
2. self._drm._artists[-1].patch --> 'Colorbar' object has no attribute 'patch'
https://github.com/USRA-STI/gdt-core/blob/6f9b15ae75b9a8fab9652ec883f9735135c62ebf/src/gdt/core/plot/drm.py#L113

The fix for 1 is easy. I still need to look into how to handle 2. I can include both fixes in a pull request after I finish running through the rest of the notebooks.

**Comment by joshuarwood** [comment]
It looks like `self._drm._artists[-1].patch.set_facecolor(self._background)` should be `self._drm._artists[-1].ax.set_facecolor(self._background)` since the patch member was removed in matplotlib 3.7. The setup.py requires matplotlib > 3.9.1

**Comment by AdamGoldstein-USRA** [comment]
Resolved in PR #71
